source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLStreamingKit_Example' do
  pod "PLStreamingKit", :path => "../"
  pod "GPUImage"
  pod "KSCrash"
end

target 'PLStreamingKit_Tests' do
  pod "PLStreamingKit", :path => "../"
end
